version: "3.4"
services:

  mongo:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:4.4.9-community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/import:/import
      - ./volumes/neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7687" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api-server:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo
      - neo4j